<a href="https://colab.research.google.com/github/Saifullah785/python-for-finance-notes/blob/main/Chapter_05_Data_Analysis_with_pandas/Chapter_05_Data_Analysis_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Analysis with pandas**

pandas Basics

**First Steps with DataFrame Class**

In [30]:
# Import the pandas library, commonly aliased as 'pd'
import pandas as pd

In [31]:
# Create a pandas DataFrame from a list of numbers
df  = pd.DataFrame([10, 20, 30, 40],
                  columns=['numbers'],
                  index=['a', 'b', 'c', 'd'])

In [32]:
# Display the DataFrame
df

numbers
a       10
b       20
c       30
d       40

In [33]:
# Access and display the index of the DataFrame
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
# Access and display the columns of the DataFrame
df.columns

Index(['numbers'], dtype='object')

In [35]:
# Access a row by its label using .loc[]
df.loc['c']

numbers    30
Name: c, dtype: int64

In [36]:
# Access multiple rows by their labels using .loc[]
df.loc[['a','d']]

numbers
a       10
d       40

In [37]:
# Access rows by their integer position using .iloc[] (slice)
df.iloc[1:3]

numbers
b       20
c       30

In [38]:
# Calculate the sum of the columns in the DataFrame
df.sum()

numbers    100
dtype: int64

In [39]:
# Apply a function (squaring each element) to the DataFrame using .apply()
df.apply(lambda x: x**2)

numbers
a      100
b      400
c      900
d     1600

In [40]:
# Square each element in the DataFrame using element-wise operation
df ** 2

numbers
a      100
b      400
c      900
d     1600

In [41]:
# Add a new column 'floats' to the DataFrame
df['floats'] = (1.5, 2.5, 3.5, 4.5)

In [42]:
# Display the DataFrame with the new column
df

numbers  floats
a       10     1.5
b       20     2.5
c       30     3.5
d       40     4.5

In [43]:
# Access and display the 'floats' column (as a Series)
df['floats']

a    1.5
b    2.5
c    3.5
d    4.5
Name: floats, dtype: float64

In [44]:
# Add another new column 'names' using a pandas Series with a specified index
df['names'] = pd.Series(['Yves', 'Sandra', 'Lilli', 'Henry'], index=['d', 'a', 'b', 'c'])

In [45]:
# Display the DataFrame with the 'names' column
df

numbers  floats   names
a       10     1.5  Sandra
b       20     2.5   Lilli
c       30     3.5   Henry
d       40     4.5    Yves

In [46]:
# Concatenate the current DataFrame with a new DataFrame containing one row, ignoring the original index
pd.concat((df, pd.DataFrame({'numbers': 100, 'floats': 5.75, 'names': 'Jil'}, index=[0,])),
               ignore_index=True)

numbers  floats   names
0       10    1.50  Sandra
1       20    2.50   Lilli
2       30    3.50   Henry
3       40    4.50    Yves
4      100    5.75     Jil

In [47]:
# Assign the result of the concatenation back to the original DataFrame variable
df = pd.concat((df, pd.DataFrame({'numbers': 100, 'floats': 5.75, 'names': 'Jil'}, index=[0,])),
               ignore_index=True)

In [48]:
# Display the updated DataFrame after concatenation
df

numbers  floats   names
0       10    1.50  Sandra
1       20    2.50   Lilli
2       30    3.50   Henry
3       40    4.50    Yves
4      100    5.75     Jil

In [49]:
# Add a new row with label 'z' and some values. Note that missing values will be NaN.
df.loc['z'] = {'names': 'Liz'}

In [50]:
# Display the DataFrame with the newly added row
df

numbers  floats   names
0     10.0    1.50  Sandra
1     20.0    2.50   Lilli
2     30.0    3.50   Henry
3     40.0    4.50    Yves
4    100.0    5.75     Jil
z      NaN     NaN     Liz

In [51]:
# Display the data types of each column in the DataFrame
df.dtypes

numbers    float64
floats     float64
names       object
dtype: object

In [52]:
# Calculate the mean of the 'numbers' and 'floats' columns
df[['numbers', 'floats']].mean()

numbers    40.00
floats      3.55
dtype: float64

In [53]:
# Calculate the standard deviation of the 'numbers' and 'floats' columns
df[['numbers', 'floats']].std()

numbers    35.355339
floats      1.662077
dtype: float64

#**Second Steps with DataFrame Class**

In [54]:
import numpy as np
import pandas as pd

In [55]:
# Set a seed for reproducibility of random number generation
np.random.seed(100)

In [56]:
# Generate a 9x4 array of random numbers from a standard normal distribution
a = np.random.standard_normal((9, 4))

In [57]:
# Display the generated NumPy array
a

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

In [58]:
# Create a pandas DataFrame from the NumPy array
df = pd.DataFrame(a)

In [59]:
# Display the DataFrame
df

0         1         2         3
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318
5  1.618982  1.541605 -0.251879 -0.842436
6  0.184519  0.937082  0.731000  1.361556
7 -0.326238  0.055676  0.222400 -1.443217
8 -0.756352  0.816454  0.750445 -0.455947

In [60]:
# Rename the columns of the DataFrame
df.columns = ['No1', 'No2', 'No3', 'No4']

In [61]:
# Display the DataFrame with the new column names
df

No1       No2       No3       No4
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318
5  1.618982  1.541605 -0.251879 -0.842436
6  0.184519  0.937082  0.731000  1.361556
7 -0.326238  0.055676  0.222400 -1.443217
8 -0.756352  0.816454  0.750445 -0.455947

In [62]:
# Calculate the mean of the 'No2' column
df['No2'].mean()

np.float64(0.7010330941456459)

In [63]:
# Generate a DatetimeIndex with 9 monthly periods starting from '2023-01-01'
dates = pd.date_range('2023-01-01', periods=9, freq='M')

/tmp/ipython-input-63-3376437583.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range('2023-01-01', periods=9, freq='M')


In [64]:
# Display the generated DatetimeIndex
dates

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='ME')

In [65]:
# Set the DataFrame's index to the generated DatetimeIndex
df.index = dates

In [66]:
# Display the DataFrame with the new DatetimeIndex
df

No1       No2       No3       No4
2023-01-31 -1.749765  0.342680  1.153036 -0.252436
2023-02-28  0.981321  0.514219  0.221180 -1.070043
2023-03-31 -0.189496  0.255001 -0.458027  0.435163
2023-04-30 -0.583595  0.816847  0.672721 -0.104411
2023-05-31 -0.531280  1.029733 -0.438136 -1.118318
2023-06-30  1.618982  1.541605 -0.251879 -0.842436
2023-07-31  0.184519  0.937082  0.731000  1.361556
2023-08-31 -0.326238  0.055676  0.222400 -1.443217
2023-09-30 -0.756352  0.816454  0.750445 -0.455947

In [67]:
# Access the underlying NumPy array of the DataFrame
df.values

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

In [68]:
# Convert the DataFrame to a NumPy array
np.array(df)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

# **Basic Analytics**

In [69]:
# Display concise summary of a DataFrame, including the index dtype and columns, non-null values and memory usage.
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9 entries, 2023-01-31 to 2023-09-30
Freq: ME
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   No1     9 non-null      float64
 1   No2     9 non-null      float64
 2   No3     9 non-null      float64
 3   No4     9 non-null      float64
dtypes: float64(4)
memory usage: 360.0 bytes


In [70]:
# Generate descriptive statistics of the DataFrame
df.describe()

No1       No2       No3       No4
count  9.000000  9.000000  9.000000  9.000000
mean  -0.150212  0.701033  0.289193 -0.387788
std    0.988306  0.457685  0.579920  0.877532
min   -1.749765  0.055676 -0.458027 -1.443217
25%   -0.583595  0.342680 -0.251879 -1.070043
50%   -0.326238  0.816454  0.222400 -0.455947
75%    0.184519  0.937082  0.731000 -0.104411
max    1.618982  1.541605  1.153036  1.361556

In [71]:
# Calculate the sum of each column in the DataFrame
df.sum()

No1   -1.351906
No2    6.309298
No3    2.602739
No4   -3.490089
dtype: float64

In [72]:
# Calculate the mean of each column in the DataFrame
df.mean()

No1   -0.150212
No2    0.701033
No3    0.289193
No4   -0.387788
dtype: float64

In [73]:
# Calculate the mean of each column in the DataFrame (axis=0 is default for columns)
df.mean(axis=0)

No1   -0.150212
No2    0.701033
No3    0.289193
No4   -0.387788
dtype: float64

In [74]:
# Calculate the mean of each row in the DataFrame (axis=1 for rows)
df.mean(axis=1)

2023-01-31   -0.126621
2023-02-28    0.161669
2023-03-31    0.010661
2023-04-30    0.200390
2023-05-31   -0.264500
2023-06-30    0.516568
2023-07-31    0.803539
2023-08-31   -0.372845
2023-09-30    0.088650
Freq: ME, dtype: float64

In [75]:
# Calculate the cumulative sum of each column in the DataFrame
df.cumsum()

No1       No2       No3       No4
2023-01-31 -1.749765  0.342680  1.153036 -0.252436
2023-02-28 -0.768445  0.856899  1.374215 -1.322479
2023-03-31 -0.957941  1.111901  0.916188 -0.887316
2023-04-30 -1.541536  1.928748  1.588909 -0.991727
2023-05-31 -2.072816  2.958480  1.150774 -2.110045
2023-06-30 -0.453834  4.500086  0.898895 -2.952481
2023-07-31 -0.269316  5.437168  1.629895 -1.590925
2023-08-31 -0.595554  5.492844  1.852294 -3.034142
2023-09-30 -1.351906  6.309298  2.602739 -3.490089

In [76]:
# Calculate the mean of the entire DataFrame using NumPy
np.mean(df)

np.float64(0.1130567313677401)

In [77]:
# Calculate the natural logarithm of each element in the DataFrame
np.log(df)

/usr/local/lib/python3.11/dist-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)


No1       No2       No3       No4
2023-01-31       NaN -1.070957  0.142398       NaN
2023-02-28 -0.018856 -0.665106 -1.508780       NaN
2023-03-31       NaN -1.366486       NaN -0.832033
2023-04-30       NaN -0.202303 -0.396425       NaN
2023-05-31       NaN  0.029299       NaN       NaN
2023-06-30  0.481797  0.432824       NaN       NaN
2023-07-31 -1.690005 -0.064984 -0.313341  0.308628
2023-08-31       NaN -2.888206 -1.503279       NaN
2023-09-30       NaN -0.202785 -0.287089       NaN

In [78]:
# Calculate the square root of the absolute value of each element in the DataFrame
np.sqrt(abs(df))

No1       No2       No3       No4
2023-01-31  1.322787  0.585389  1.073795  0.502430
2023-02-28  0.990616  0.717091  0.470297  1.034429
2023-03-31  0.435311  0.504977  0.676777  0.659669
2023-04-30  0.763934  0.903796  0.820196  0.323127
2023-05-31  0.728890  1.014757  0.661918  1.057506
2023-06-30  1.272392  1.241614  0.501876  0.917843
2023-07-31  0.429556  0.968030  0.854986  1.166857
2023-08-31  0.571173  0.235958  0.471593  1.201340
2023-09-30  0.869685  0.903578  0.866282  0.675238

In [79]:
# Calculate the sum of the square root of the absolute value of each column in the DataFrame
np.sqrt(abs(df)).sum()

No1    7.384345
No2    7.075190
No3    6.397719
No4    7.538440
dtype: float64

In [80]:
# Perform element-wise arithmetic operation: multiply by 100 and add 100
100 * df + 100

No1         No2         No3         No4
2023-01-31  -74.976547  134.268040  215.303580   74.756396
2023-02-28  198.132079  151.421884  122.117967   -7.004333
2023-03-31   81.050417  125.500144   54.197301  143.516349
2023-04-30   41.640495  181.684707  167.272081   89.558886
2023-05-31   46.871962  202.973269   56.186438  -11.831825
2023-06-30  261.898166  254.160517   74.812086   15.756426
2023-07-31  118.451869  193.708220  173.100034  236.155613
2023-08-31   67.376194  105.567601  122.239961  -44.321700
2023-09-30   24.364769  181.645401  175.044476   54.405307