<a href="https://colab.research.google.com/github/Saifullah785/python-for-finance-notes/blob/main/Chapter_04_Numerical_Computing_with_NumPy/Chapter_04_Numerical_Computing_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numerical Computing with NumPy**

**Arrays with Python Lists**

In [ ]:
# Define a Python list 'v' with some numerical values.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Display the list 'v'.
v

[0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
# Create a list 'm' containing three copies of the list 'v'.
m = [v, v, v]
# Display the list of lists 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Access and display the second element (at index 1) of the list of lists 'm'.
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
# Access and display the first element (at index 0) of the second list (at index 1) within 'm'.
m[1][0]

0.5

In [ ]:
# Define two Python lists 'v1' and 'v2'.
v1 = [0.5, 1.5]
# Display 'v1'.
v1

v2 = [1, 2]
# Display 'v2'.
v2

# Create a list of lists 'm' containing 'v1' and 'v2'.
m = [v1, v2]
# Display 'm'.
m

# Create a list of lists of lists 'c' containing two copies of 'm'.
c = [m, m]
# Display 'c'.
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [ ]:
# Access and display the first element (at index 0) of the second list (at index 1) within the second list (at index 1) of 'c'.
c[1][1][0]

1

In [ ]:
# Redefine the list 'v'.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Redefine the list of lists 'm' with three copies of 'v'.
m = [v, v, v]
# Display 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Modify the first element of the list 'v' to the string 'Python'.
v [0] = 'Python'
# Display 'm'. Note that because 'm' contains references to 'v', the change in 'v' is reflected in 'm'.
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Import the deepcopy function from the copy module.
from copy import deepcopy
# Redefine the list 'v'.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Create a list of lists 'm' with three independent copies of 'v' using deepcopy.
m = 3 * [deepcopy (v), ]
# Display 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Modify the first element of the list 'v' to the string 'Python'.
v[0] = 'Python'
# Display 'm'. Note that because deepcopy was used, the change in 'v' does not affect the lists within 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

# **Interlude: Python Array Class**

In [ ]:
# Define a Python list 'v' with some numerical values.
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
# Import the array module.
import array

In [ ]:
# Create an array 'a' of type 'f' (float) from the list 'v'.
a = array.array('f', v)
# Display the array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [ ]:
# Append a value (0.5) to the array 'a'.
a.append(0.5)
# Display the modified array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [ ]:
# Extend the array 'a' with elements from a list ([5.0, 6.75]).
a.extend([5.0, 6.75])
# Display the modified array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [ ]:
# Attempt to multiply the array 'a' by 2. For array.array, this concatenates the array with itself.
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [ ]:
# Convert the array 'a' back to a Python list.
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [ ]:
# Open a file named 'array.apy' in binary write mode ('wb').
f = open('array.apy', 'wb')
# Write the contents of array 'a' to the file.
a.tofile(f)
# Close the file.
f.close()

In [ ]:
# Open a file named 'array.apy' in binary write mode ('wb') using a 'with' statement, which ensures the file is closed automatically.
with open ('array.apy', 'wb') as f:
  # Write the contents of array 'a' to the file.
  a.tofile(f)

In [ ]:
# Execute a shell command to list files starting with 'arr' in the current directory, showing file permissions, number of links, owner, group, size, and modification time.
!ls -n arr*

-rw-r--r-- 1 0 0 32 Jul 19 13:59 array.apy


In [ ]:
# Create an empty array 'b' of type 'f' (float).
b = array.array('f')
# Display the empty array 'b'.
b

array('f')

In [ ]:
# Open the file 'array.apy' in binary read mode ('rb').
with open('array.apy', 'rb') as f:
  # Read 2 elements of type 'f' (float) from the file into array 'b'.
  b.fromfile(f, 2)

In [ ]:
# Display the array 'b' after reading data from the file.
b

array('f', [0.5, 0.75])

In [ ]:
# Create an empty array 'b' of type 'd' (double).
b = array.array('d')
# Display the empty array 'b'.
b

array('d')

In [ ]:
# Open the file 'array.apy' in binary read mode ('rb').
with open('array.apy', 'rb') as f:
    # Read 2 elements of type 'd' (double) from the file into array 'b'. Note that reading floats as doubles can lead to unexpected values due to different byte sizes.
    b.fromfile(f, 2)

In [ ]:
# Display the array 'b' after attempting to read float data as doubles from the file.
b

array('d', [0.0004882813645963324, 0.12500002956949174])

# **Regular NumPy Arrays**

The Basics





In [ ]:
# Import the NumPy library, commonly aliased as np.
import numpy as np

In [ ]:
# Create a NumPy array named 'a' with specified numerical values.
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
# Display the array 'a'.
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
# Check and display the data type of the object 'a'.
type(a)

numpy.ndarray

In [ ]:
# Create a NumPy array named 'a' with string elements.
a = np.array(['a', 'b', 'c'])
# Display the array 'a'.
a

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
# Create a NumPy array named 'a' using arange, generating values from 2 up to (but not including) 20 with a step of 2.
a = np.arange(2, 20, 2)
# Display the array 'a'.
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Create a NumPy array named 'a' using arange, generating 8 values starting from 0, with a specified data type of float32.
a = np.arange(8, dtype=np.float32)
# Display the array 'a'.
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [ ]:
# Access and display elements of array 'a' from index 5 to the end (slicing).
a[5:]

array([5., 6., 7.], dtype=float32)

In [ ]:
# Access and display elements of array 'a' from the beginning up to (but not including) index 2 (slicing).
a[:2]

array([0., 1.], dtype=float32)

In [ ]:
# Display the sum method of the array 'a'. Note: This shows the method object, not the result of the sum.
a.sum

<function ndarray.sum>

In [ ]:
# Calculate and display the standard deviation of the array 'a'.
a.std()

np.float32(2.291288)

In [ ]:
# Calculate and display the cumulative sum of the elements in array 'a'.
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.], dtype=float32)

In [ ]:
# Define a Python list 'l'.
l = [0., 0.5, 1.5, 3., 5.]
# Multiply the list 'l' by 2. For lists, this results in concatenation.
2 *l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [ ]:
# Display the current state of array 'a'.
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [ ]:
# Multiply each element of the NumPy array 'a' by 2 (element-wise multiplication).
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

In [ ]:
# Raise each element of the NumPy array 'a' to the power of 2 (element-wise exponentiation).
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.], dtype=float32)

In [ ]:
# Calculate 2 raised to the power of each element in array 'a' (element-wise exponentiation).
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.], dtype=float32)

In [ ]:
# Raise each element of array 'a' to the power of itself (element-wise exponentiation).
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05], dtype=float32)

In [ ]:
# Calculate the exponential of each element in array 'a' (e raised to the power of each element).
np.exp(a)

array([1.0000000e+00, 2.7182820e+00, 7.3890557e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342877e+02, 1.0966332e+03],
      dtype=float32)

In [ ]:
# Calculate the square root of each element in array 'a'.
np.sqrt(a)

array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512], dtype=float32)

In [ ]:
# Calculate the square root of the scalar value 2.5 using NumPy's sqrt function.
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [ ]:
# Import the math module.
import math

In [ ]:
# Calculate the square root of the scalar value 2.5 using Python's built-in math.sqrt function.
math.sqrt(2.5)

1.5811388300841898

In [ ]:
# Measure the execution time of calculating the square root of 2.5 using NumPy's sqrt function.
%timeit np.sqrt(2.5)

1.53 µs ± 407 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# Measure the execution time of calculating the square root of 2.5 using Python's built-in math.sqrt function.
%timeit math.sqrt(2.5)

87.4 ns ± 39.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# **Multiple Dimensions**

In [ ]:
import numpy as np
# Create a 2D NumPy array 'b' by stacking array 'a' and 'a' multiplied by 2.
b = np.array([a, a * 2])
# Display the array 'b'.
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]], dtype=float32)

In [ ]:
# Access and display the first row (at index 0) of the 2D array 'b'.
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [ ]:
# Access and display the element at the first row (index 0) and third column (index 2) of array 'b'.
b[0, 2]

np.float32(2.0)

In [ ]:
# Access and display elements from all rows (:) at the second column (index 1) of array 'b'.
b[:,1]

array([1., 2.], dtype=float32)

In [ ]:
# Calculate and display the sum of all elements in the array 'b'.
b.sum()

np.float32(84.0)

In [ ]:
# Calculate and display the sum of elements along columns (axis=0) in array 'b'.
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.], dtype=float32)

In [ ]:
# Calculate and display the sum of elements along rows (axis=1) in array 'b'.
b.sum(axis=1)

array([28., 56.], dtype=float32)

In [ ]:
# Create a 2x3 NumPy array 'c' filled with zeros, with integer data type and C-style order.
c = np.zeros((2, 3), dtype='i', order='C')
# Display array 'c'.
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
# Create a 3D NumPy array 'c' of shape (2, 3, 4) filled with ones, with integer data type and C-style order.
c = np.ones((2, 3, 4), dtype='i', order='C')
# Display array 'c'.
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [ ]:
# Create a new array 'd' with the same shape and data type as array 'c', filled with uninitialized data (effectively zeros in many cases), with float16 data type and C-style order.
d = np.zeros_like(c, dtype='f16', order='C')
# Display array 'd'.
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [ ]:
# Create a new array 'd' with the same shape and data type as array 'c', filled with ones, with float16 data type and C-style order.
d = np.ones_like(c, dtype='f16', order='C')
# Display array 'd'.
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [ ]:
# Create a new array 'e' of shape (2, 3, 2) with uninitialized data. The contents will be whatever is in memory at that location.
e = np.empty((2, 3, 2))
# Display array 'e'.
e

array([[[6.75898327e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
# Create a new array 'f' with the same shape and data type as array 'c', filled with uninitialized data.
f = np.empty_like(c)
# Display array 'f'.
f

array([[[46126841,    31852,        0,        0],
        [       0,        0,        0,        0],
        [       0,        0,        0,        0]],

       [[       0,        0,        0,        0],
        [       0,        0,        0,        0],
        [       0,        0,        0,        0]]], dtype=int32)

In [ ]:
# Create a 5x5 identity matrix using np.eye().
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Create a NumPy array 'g' with 12 evenly spaced values between 5 and 15 (inclusive).
g = np.linspace(5, 15, 12)
# Display array 'g'.
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

# **Meta information**

In [ ]:
# Display the total number of elements in the array 'g'.
g.size

12

In [ ]:
# Display the size in bytes of each element in the array 'g'.
g.itemsize

8

In [ ]:
# Display the number of dimensions (axes) of the array 'g'.
g.ndim

1

In [ ]:
# Display the shape of the array 'g' (a tuple indicating the size of each dimension).
g.shape

(12,)

In [ ]:
# Display the data type of the elements in the array 'g'.
g.dtype

dtype('float64')

In [ ]:
# Display the total number of bytes consumed by the elements of the array 'g'.
g.nbytes

96

# **Reshaping, Resizing, Stacking, Flattening**

In [ ]:
g = np.arange(15)
# Display the array 'g'.
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Display the shape of the array 'g'.
g.shape

(15,)

In [ ]:
# Display the shape of the array 'g' using np.shape().
np.shape(g)

(15,)

In [ ]:
# Reshape the array 'g' into a 3x5 matrix and display the result.
g.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# Reshape the array 'g' into a 5x3 matrix and assign it to variable 'h', then display 'h'.
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# Display the transpose of array 'h'.
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [ ]:
# Display the transpose of array 'h' using the transpose() method.
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [ ]:
# Display the current state of array 'g'.
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Resize the array 'g' to a shape of (3, 1) and display the result.
np.resize(g, (3, 1))

array([[0],
       [1],
       [2]])

In [ ]:
# Resize the array 'g' to a shape of (1, 5) and display the result.
np.resize(g, (1, 5))

array([[0, 1, 2, 3, 4]])

In [ ]:
# Resize the array 'g' to a shape of (2, 5) and display the result.
np.resize(g, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Resize the array 'g' to a shape of (5, 4), assign it to 'n', and display 'n'. Note that resizing to a larger size repeats the original array elements.
n = np.resize(g, (5, 4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [ ]:
# Display the current state of array 'h'.
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# Horizontally stack array 'h' and 'h' multiplied by 2, then display the result.
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [ ]:
# Vertically stack array 'h' and 'h' multiplied by 0.5, then display the result.
np.vstack((h, 0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [ ]:
# Display the current state of array 'h'.
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# Flatten the array 'h' into a 1D array (row-major order by default) and display the result.
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Flatten the array 'h' into a 1D array using C-style (row-major) order and display the result.
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Flatten the array 'h' into a 1D array using Fortran-style (column-major) order and display the result.
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [ ]:
# Iterate through the flattened array 'h' (row-major order by default) and print each element followed by a comma.
for i in h.flat:
  print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [ ]:
# Iterate through the array 'h' using ravel (which returns a view or copy depending on the order and original array) in C-style (row-major) order and print each element followed by a comma.
for i in h.ravel(order='C'):
  print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [ ]:
# Iterate through the array 'h' using ravel (which returns a view or copy depending on the order and original array) in Fortran-style (column-major) order and print each element followed by a comma.
for i in h.ravel(order='F'):
  print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

#**Boolean Arrays**

In [ ]:
# Display the array 'h'.
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# Perform a boolean comparison to find elements in 'h' greater than 8 and display the resulting boolean array.
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Perform a boolean comparison to find elements in 'h' less than or equal to 7 and display the resulting boolean array.
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Perform a boolean comparison to find elements in 'h' equal to 5 and display the resulting boolean array.
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Convert the boolean array (h == 5) to an integer array, where True becomes 1 and False becomes 0, and display the result.
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Perform a boolean operation to find elements in 'h' greater than 4 AND less than or equal to 12, and display the resulting boolean array.
(h > 4) & ( h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [ ]:
# Use the boolean array (h > 8) to index 'h' and display only the elements from 'h' where the condition is True.
h[h > 8]

array([ 9, 10, 11, 12, 13, 14])

In [ ]:
# Use the boolean array from the combined condition ((h > 4) & (h <= 12)) to index 'h' and display only the elements from 'h' where the combined condition is True.
h[(h > 4) & (h <=12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Use the boolean array from the combined condition ((h < 4) | (h >= 12)) to index 'h' and display only the elements from 'h' where the combined condition is True.
h[(h < 4) | (h >= 12)]

array([ 0,  1,  2,  3, 12, 13, 14])

In [ ]:
# Use np.where to replace elements in 'h' based on the condition h > 7: if True, replace with 1; if False, replace with 0. Display the result.
np.where(h > 7, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Use np.where to replace elements in 'h' based on the condition h % 2 == 0 (whether the element is even): if True, replace with 'even'; if False, replace with 'odd'. Display the result.
np.where(h % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [ ]:
# Use np.where to replace elements in 'h' based on the condition h <= 7: if True, replace with h * 2; if False, replace with h / 2. Display the result.
np.where(h <= 7, h * 2, h / 2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

#**Speed Comparison**

In [ ]:
# Import the random module and set the value of I to 5000. I will be used to define the size of a matrix.
import random
I = 5000

In [ ]:
# Measure the time taken to create a list of lists ('mat') of size I x I, filled with random numbers from a Gaussian distribution using Python's built-in random.gauss.
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]

CPU times: user 16.9 s, sys: 803 ms, total: 17.8 s
Wall time: 20.4 s


In [ ]:
# Display the first 5 elements of the first row of the list of lists 'mat'.
mat[0][:5]

[-0.31589902274896553,
 -0.4607851392995981,
 -0.009265930555524476,
 0.6893909496639743,
 -0.5206818698912445]

In [ ]:
# Measure the time taken to calculate the sum of all elements in the list of lists 'mat' using nested list comprehensions and Python's built-in sum.
%time sum([sum(l) for l in mat])

CPU times: user 189 ms, sys: 0 ns, total: 189 ms
Wall time: 191 ms


302.348352862778

In [ ]:
# Import the sys module and calculate the total memory size in bytes of the list of lists 'mat' by summing the size of each inner list using sys.getsizeof.
import sys
sum([sys.getsizeof(l) for l in mat])

209400000

In [ ]:
# Measure the time taken to create a NumPy array ('mat') of size I x I, filled with random numbers from a standard normal distribution using np.random.standard_normal.
%time mat = np.random.standard_normal((I, I))

CPU times: user 767 ms, sys: 61.9 ms, total: 829 ms
Wall time: 826 ms


In [ ]:
# Measure the time taken to calculate the sum of all elements in the NumPy array 'mat' using the array's built-in sum() method.
%time mat.sum()

CPU times: user 18.3 ms, sys: 0 ns, total: 18.3 ms
Wall time: 17.6 ms


np.float64(2840.8252587626025)

In [ ]:
# Display the total number of bytes consumed by the elements of the NumPy array 'mat' using the nbytes attribute.
mat.nbytes

200000000

In [ ]:
# Display the total memory size in bytes of the NumPy array 'mat' using sys.getsizeof.
sys.getsizeof(mat)

200000128

# **Structured Arrays**

In [57]:
# Import the NumPy library, commonly aliased as np.
import numpy as np

In [58]:
# Define a data type 'dt' for a structured array with fields for Name (string, max 10 chars),
# Age (4-byte integer), Height (float), and Children/Pets (a tuple of two 4-byte integers).
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [59]:
# Display the defined data type 'dt'.
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [60]:
# Define a data type 'dt' for a structured array using a dictionary,
# specifying names and formats for fields Name, Age, Height, and Children/Pets.
# 'O' stands for object, 'int' for integer, 'float' for float. The comma in 'int,int'
# indicates a nested structure for Children/Pets.
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],
               'formats': 'O int float int,int'.split()})

In [61]:
# Display the defined data type 'dt'.
dt

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [62]:
# Create a structured NumPy array 's' with two records, using the data type 'dt'.
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)

In [63]:
# Display the structured array 's'.
s

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [64]:
# Display the type of the object 's', which is a NumPy ndarray.
type(s)

numpy.ndarray

In [65]:
# Access and display the 'Name' field from the structured array 's'.
s['Name']

array(['Smith', 'Jones'], dtype=object)

In [66]:
# Access the 'Height' field of the structured array 's' and calculate its mean.
s['Height'].mean()

np.float64(1.775)

In [67]:
# Access and display the first record (at index 0) of the structured array 's'.
s[0]

np.void(('Smith', 45, 1.83, (0, 1)), dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [68]:
# Access and display the 'Age' field from the second record (at index 1) of the structured array 's'.
s[1]['Age']

np.int64(53)

# **Vectorization of Code**

In [69]:
# Set the random seed for reproducibility.
np.random.seed(100)
# Create a 4x3 array 'r' with values from 0 to 11 and reshape it.
r = np.arange(12).reshape((4, 3))
# Create a 4x3 array 's' by multiplying 'r' by 0.5.
s = np.arange(12).reshape((4, 3)) * 0.5

In [70]:
# Display array 'r'.
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
# Display array 's'.
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [72]:
# Perform element-wise addition of arrays 'r' and 's', and display the result.
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [73]:
# Add the scalar value 3 to each element of array 'r' (broadcasting), and display the result.
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
# Multiply each element of array 'r' by 2 (broadcasting), and display the result.
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [75]:
# Perform combined broadcasting operations: multiply 'r' by 2 and add 3 to each element, then display the result.
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [76]:
# Display the current state of array 'r'.
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [77]:
# Display the shape of array 'r'.
r.shape

(4, 3)

In [78]:
# Create a 1D array 's' using arange with a step of 4.
s = np.arange(0, 12, 4)
# Display array 's'.
s

array([0, 4, 8])

In [79]:
# Add array 's' to array 'r'. NumPy broadcasts 's' to match the shape of 'r' by repeating the 1D array across the rows of 'r'.
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [80]:
# Create a 1D array 's' using arange with a step of 3.
s = np.arange(0, 12, 3)
# Display array 's'.
s

array([0, 3, 6, 9])

In [85]:
# This code causes an intentional error because the shapes of 'r' (4, 3) and 's' (4,) are not compatible for direct addition without reshaping/broadcasting rules being met.
# r + s

In [87]:
# Transpose array 'r' (shape becomes (3, 4)) and add array 's' (shape (4,)). NumPy broadcasts 's' to match the columns of the transposed 'r'.
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [88]:
# Reshape the 1D array 's' (shape (4,)) into a 2D array with a single column (shape (4, 1)).
sr = s.reshape(-1, 1)
# Display the reshaped array 'sr'.
sr

array([[0],
       [3],
       [6],
       [9]])

In [89]:
# Display the shape of the reshaped array 'sr'.
sr.shape

(4, 1)

In [90]:
# Add array 'r' (shape (4, 3)) to the reshaped array 's' (shape (4, 1)). NumPy broadcasts the reshaped 's' across the columns of 'r'.
r + s.reshape(-1, 1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [91]:
# Define a Python function 'f' that takes a single argument 'x' and returns 3 times 'x' plus 5.
def f(x):
  return 3 * x + 5

In [92]:
# Call the function 'f' with a scalar value (0.5) and display the result.
f (0.5)

6.5

In [93]:
# Call the function 'f' with the NumPy array 'r'. Due to NumPy's vectorization, the function is applied element-wise to the array. Display the result.
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

#**Memory Layout**

In [94]:
# Create a NumPy array 'x' of shape (1000000, 5) filled with random numbers from a standard normal distribution.
x = np.random.standard_normal((1000000, 5))

In [95]:
# Create a NumPy array 'y' by performing element-wise operations on array 'x' (multiply by 2 and add 3).
y = 2 * x + 3

In [96]:
# Create a new NumPy array 'C' by stacking arrays 'x' and 'y' along a new axis (axis 0).
# The resulting array 'C' has shape (2, 1000000, 5).
# The 'order='C'' argument specifies C-style (row-major) memory layout.
C = np.array((x, y), order='C')

In [97]:
# Create a new NumPy array 'F' by stacking arrays 'x' and 'y' along a new axis (axis 0).
# The resulting array 'F' has shape (2, 1000000, 5).
# The 'order='F'' argument specifies Fortran-style (column-major) memory layout.
F = np.array((x, y), order='F')

In [98]:
# Assign the scalar value 0.0 to the variables 'x' and 'y'. This releases the memory previously held by the large arrays.
x = 0.0; y = 0.0

In [99]:
# Access the first two slices along the first axis of array 'C' and round the elements to 2 decimal places. Display the result.
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [100]:
# Measure the execution time of calculating the sum of all elements in the C-ordered array 'C'.
%timeit C.sum()

7.88 ms ± 592 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [101]:
# Measure the execution time of calculating the sum of all elements in the Fortran-ordered array 'F'.
%timeit F.sum()

7.3 ms ± 62.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [102]:
# Measure the execution time of calculating the sum of elements along axis 0 (columns) in the C-ordered array 'C'.
%timeit C.sum(axis=0)

24.6 ms ± 459 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [103]:
# Measure the execution time of calculating the sum of elements along axis 1 (rows) in the C-ordered array 'C'.
%timeit C.sum(axis=1)

50.6 ms ± 6.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [104]:
# Measure the execution time of calculating the sum of elements along axis 0 (columns) in the Fortran-ordered array 'F'.
%timeit F.sum(axis=0)

106 ms ± 202 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [105]:
# Measure the execution time of calculating the sum of elements along axis 1 (rows) in the Fortran-ordered array 'F'.
%timeit F.sum(axis=1)

96.2 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [106]:
# Assign the scalar value 0.0 to the variables 'F' and 'C'. This releases the memory previously held by the large arrays.
F = 0.0; C = 0.0