<a href="https://colab.research.google.com/github/Saifullah785/python-for-finance-notes/blob/main/Chapter_04_Numerical_Computing_with_NumPy/Chapter_04_Numerical_Computing_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numerical Computing with NumPy**

**Arrays with Python Lists**

In [ ]:
# Define a Python list 'v' with some numerical values.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Display the list 'v'.
v

[0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
# Create a list 'm' containing three copies of the list 'v'.
m = [v, v, v]
# Display the list of lists 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Access and display the second element (at index 1) of the list of lists 'm'.
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
# Access and display the first element (at index 0) of the second list (at index 1) within 'm'.
m[1][0]

0.5

In [ ]:
# Define two Python lists 'v1' and 'v2'.
v1 = [0.5, 1.5]
# Display 'v1'.
v1

v2 = [1, 2]
# Display 'v2'.
v2

# Create a list of lists 'm' containing 'v1' and 'v2'.
m = [v1, v2]
# Display 'm'.
m

# Create a list of lists of lists 'c' containing two copies of 'm'.
c = [m, m]
# Display 'c'.
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [ ]:
# Access and display the first element (at index 0) of the second list (at index 1) within the second list (at index 1) of 'c'.
c[1][1][0]

1

In [ ]:
# Redefine the list 'v'.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Redefine the list of lists 'm' with three copies of 'v'.
m = [v, v, v]
# Display 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Modify the first element of the list 'v' to the string 'Python'.
v [0] = 'Python'
# Display 'm'. Note that because 'm' contains references to 'v', the change in 'v' is reflected in 'm'.
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Import the deepcopy function from the copy module.
from copy import deepcopy
# Redefine the list 'v'.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Create a list of lists 'm' with three independent copies of 'v' using deepcopy.
m = 3 * [deepcopy (v), ]
# Display 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [ ]:
# Modify the first element of the list 'v' to the string 'Python'.
v[0] = 'Python'
# Display 'm'. Note that because deepcopy was used, the change in 'v' does not affect the lists within 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

# **Interlude: Python Array Class**

In [ ]:
# Define a Python list 'v' with some numerical values.
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [ ]:
# Import the array module.
import array

In [ ]:
# Create an array 'a' of type 'f' (float) from the list 'v'.
a = array.array('f', v)
# Display the array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [ ]:
# Append a value (0.5) to the array 'a'.
a.append(0.5)
# Display the modified array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [ ]:
# Extend the array 'a' with elements from a list ([5.0, 6.75]).
a.extend([5.0, 6.75])
# Display the modified array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [ ]:
# Attempt to multiply the array 'a' by 2. For array.array, this concatenates the array with itself.
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [ ]:
# Convert the array 'a' back to a Python list.
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [ ]:
# Open a file named 'array.apy' in binary write mode ('wb').
f = open('array.apy', 'wb')
# Write the contents of array 'a' to the file.
a.tofile(f)
# Close the file.
f.close()

In [ ]:
# Open a file named 'array.apy' in binary write mode ('wb') using a 'with' statement, which ensures the file is closed automatically.
with open ('array.apy', 'wb') as f:
  # Write the contents of array 'a' to the file.
  a.tofile(f)

In [ ]:
# Execute a shell command to list files starting with 'arr' in the current directory, showing file permissions, number of links, owner, group, size, and modification time.
!ls -n arr*

-rw-r--r-- 1 0 0 32 Jul 11 16:55 array.apy


In [ ]:
# Create an empty array 'b' of type 'f' (float).
b = array.array('f')
# Display the empty array 'b'.
b

array('f')

In [ ]:
# Open the file 'array.apy' in binary read mode ('rb').
with open('array.apy', 'rb') as f:
  # Read 2 elements of type 'f' (float) from the file into array 'b'.
  b.fromfile(f, 2)

In [ ]:
# Display the array 'b' after reading data from the file.
b

array('f', [0.5, 0.75])

In [ ]:
# Create an empty array 'b' of type 'd' (double).
b = array.array('d')
# Display the empty array 'b'.
b

array('d')

In [ ]:
# Open the file 'array.apy' in binary read mode ('rb').
with open('array.apy', 'rb') as f:
    # Read 2 elements of type 'd' (double) from the file into array 'b'. Note that reading floats as doubles can lead to unexpected values due to different byte sizes.
    b.fromfile(f, 2)

In [ ]:
# Display the array 'b' after attempting to read float data as doubles from the file.
b

array('d', [0.0004882813645963324, 0.12500002956949174])

# **Regular NumPy Arrays**

The Basics





In [1]:
# Import the NumPy library, commonly aliased as np.
import numpy as np

In [2]:
# Create a NumPy array named 'a' with specified numerical values.
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
# Display the array 'a'.
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [3]:
# Check and display the data type of the object 'a'.
type(a)

numpy.ndarray

In [4]:
# Create a NumPy array named 'a' with string elements.
a = np.array(['a', 'b', 'c'])
# Display the array 'a'.
a

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
# Create a NumPy array named 'a' using arange, generating values from 2 up to (but not including) 20 with a step of 2.
a = np.arange(2, 20, 2)
# Display the array 'a'.
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Create a NumPy array named 'a' using arange, generating 8 values starting from 0, with a specified data type of float32.
a = np.arange(8, dtype=np.float32)
# Display the array 'a'.
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [7]:
# Access and display elements of array 'a' from index 5 to the end (slicing).
a[5:]

array([5., 6., 7.], dtype=float32)

In [8]:
# Access and display elements of array 'a' from the beginning up to (but not including) index 2 (slicing).
a[:2]

array([0., 1.], dtype=float32)

In [9]:
# Display the sum method of the array 'a'. Note: This shows the method object, not the result of the sum.
a.sum

<function ndarray.sum>

In [10]:
# Calculate and display the standard deviation of the array 'a'.
a.std()

np.float32(2.291288)

In [11]:
# Calculate and display the cumulative sum of the elements in array 'a'.
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.], dtype=float32)

In [12]:
# Define a Python list 'l'.
l = [0., 0.5, 1.5, 3., 5.]
# Multiply the list 'l' by 2. For lists, this results in concatenation.
2 *l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [13]:
# Display the current state of array 'a'.
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [14]:
# Multiply each element of the NumPy array 'a' by 2 (element-wise multiplication).
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

In [15]:
# Raise each element of the NumPy array 'a' to the power of 2 (element-wise exponentiation).
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.], dtype=float32)

In [16]:
# Calculate 2 raised to the power of each element in array 'a' (element-wise exponentiation).
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.], dtype=float32)

In [17]:
# Raise each element of array 'a' to the power of itself (element-wise exponentiation).
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05], dtype=float32)

In [18]:
# Calculate the exponential of each element in array 'a' (e raised to the power of each element).
np.exp(a)

array([1.0000000e+00, 2.7182820e+00, 7.3890557e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342877e+02, 1.0966332e+03],
      dtype=float32)

In [20]:
# Calculate the square root of each element in array 'a'.
np.sqrt(a)

array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512], dtype=float32)

In [21]:
# Calculate the square root of the scalar value 2.5 using NumPy's sqrt function.
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [22]:
# Import the math module.
import math

In [23]:
# Calculate the square root of the scalar value 2.5 using Python's built-in math.sqrt function.
math.sqrt(2.5)

1.5811388300841898

In [24]:
# Measure the execution time of calculating the square root of 2.5 using NumPy's sqrt function.
%timeit np.sqrt(2.5)

828 ns ± 10.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
# Measure the execution time of calculating the square root of 2.5 using Python's built-in math.sqrt function.
%timeit math.sqrt(2.5)

40.3 ns ± 0.917 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# **Multiple Dimensions**