<a href="https://colab.research.google.com/github/Saifullah785/python-for-finance-notes/blob/main/Chapter_04_Numerical_Computing_with_NumPy/Chapter_04_Numerical_Computing_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numerical Computing with NumPy**

**Arrays with Python Lists**

In [1]:
# Define a Python list 'v' with some numerical values.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Display the list 'v'.
v

[0.5, 0.75, 1.0, 1.5, 2.0]

In [2]:
# Create a list 'm' containing three copies of the list 'v'.
m = [v, v, v]
# Display the list of lists 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
# Access and display the second element (at index 1) of the list of lists 'm'.
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
# Access and display the first element (at index 0) of the second list (at index 1) within 'm'.
m[1][0]

0.5

In [5]:
# Define two Python lists 'v1' and 'v2'.
v1 = [0.5, 1.5]
# Display 'v1'.
v1

v2 = [1, 2]
# Display 'v2'.
v2

# Create a list of lists 'm' containing 'v1' and 'v2'.
m = [v1, v2]
# Display 'm'.
m

# Create a list of lists of lists 'c' containing two copies of 'm'.
c = [m, m]
# Display 'c'.
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
# Access and display the first element (at index 0) of the second list (at index 1) within the second list (at index 1) of 'c'.
c[1][1][0]

1

In [7]:
# Redefine the list 'v'.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Redefine the list of lists 'm' with three copies of 'v'.
m = [v, v, v]
# Display 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
# Modify the first element of the list 'v' to the string 'Python'.
v [0] = 'Python'
# Display 'm'. Note that because 'm' contains references to 'v', the change in 'v' is reflected in 'm'.
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [9]:
# Import the deepcopy function from the copy module.
from copy import deepcopy
# Redefine the list 'v'.
v = [0.5, 0.75, 1.0, 1.5, 2.0]
# Create a list of lists 'm' with three independent copies of 'v' using deepcopy.
m = 3 * [deepcopy (v), ]
# Display 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
# Modify the first element of the list 'v' to the string 'Python'.
v[0] = 'Python'
# Display 'm'. Note that because deepcopy was used, the change in 'v' does not affect the lists within 'm'.
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

# **Interlude: Python Array Class**

In [11]:
# Define a Python list 'v' with some numerical values.
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [12]:
# Import the array module.
import array

In [13]:
# Create an array 'a' of type 'f' (float) from the list 'v'.
a = array.array('f', v)
# Display the array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [14]:
# Append a value (0.5) to the array 'a'.
a.append(0.5)
# Display the modified array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [15]:
# Extend the array 'a' with elements from a list ([5.0, 6.75]).
a.extend([5.0, 6.75])
# Display the modified array 'a'.
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [16]:
# Attempt to multiply the array 'a' by 2. For array.array, this concatenates the array with itself.
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [17]:
# Convert the array 'a' back to a Python list.
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [18]:
# Open a file named 'array.apy' in binary write mode ('wb').
f = open('array.apy', 'wb')
# Write the contents of array 'a' to the file.
a.tofile(f)
# Close the file.
f.close()

In [19]:
# Open a file named 'array.apy' in binary write mode ('wb') using a 'with' statement, which ensures the file is closed automatically.
with open ('array.apy', 'wb') as f:
  # Write the contents of array 'a' to the file.
  a.tofile(f)

In [20]:
# Execute a shell command to list files starting with 'arr' in the current directory, showing file permissions, number of links, owner, group, size, and modification time.
!ls -n arr*

-rw-r--r-- 1 0 0 32 Jul 18 17:27 array.apy


In [21]:
# Create an empty array 'b' of type 'f' (float).
b = array.array('f')
# Display the empty array 'b'.
b

array('f')

In [22]:
# Open the file 'array.apy' in binary read mode ('rb').
with open('array.apy', 'rb') as f:
  # Read 2 elements of type 'f' (float) from the file into array 'b'.
  b.fromfile(f, 2)

In [23]:
# Display the array 'b' after reading data from the file.
b

array('f', [0.5, 0.75])

In [24]:
# Create an empty array 'b' of type 'd' (double).
b = array.array('d')
# Display the empty array 'b'.
b

array('d')

In [25]:
# Open the file 'array.apy' in binary read mode ('rb').
with open('array.apy', 'rb') as f:
    # Read 2 elements of type 'd' (double) from the file into array 'b'. Note that reading floats as doubles can lead to unexpected values due to different byte sizes.
    b.fromfile(f, 2)

In [26]:
# Display the array 'b' after attempting to read float data as doubles from the file.
b

array('d', [0.0004882813645963324, 0.12500002956949174])

# **Regular NumPy Arrays**

The Basics





In [27]:
# Import the NumPy library, commonly aliased as np.
import numpy as np

In [28]:
# Create a NumPy array named 'a' with specified numerical values.
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
# Display the array 'a'.
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
# Check and display the data type of the object 'a'.
type(a)

numpy.ndarray

In [30]:
# Create a NumPy array named 'a' with string elements.
a = np.array(['a', 'b', 'c'])
# Display the array 'a'.
a

array(['a', 'b', 'c'], dtype='<U1')

In [31]:
# Create a NumPy array named 'a' using arange, generating values from 2 up to (but not including) 20 with a step of 2.
a = np.arange(2, 20, 2)
# Display the array 'a'.
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# Create a NumPy array named 'a' using arange, generating 8 values starting from 0, with a specified data type of float32.
a = np.arange(8, dtype=np.float32)
# Display the array 'a'.
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [33]:
# Access and display elements of array 'a' from index 5 to the end (slicing).
a[5:]

array([5., 6., 7.], dtype=float32)

In [34]:
# Access and display elements of array 'a' from the beginning up to (but not including) index 2 (slicing).
a[:2]

array([0., 1.], dtype=float32)

In [35]:
# Display the sum method of the array 'a'. Note: This shows the method object, not the result of the sum.
a.sum

<function ndarray.sum>

In [36]:
# Calculate and display the standard deviation of the array 'a'.
a.std()

np.float32(2.291288)

In [37]:
# Calculate and display the cumulative sum of the elements in array 'a'.
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.], dtype=float32)

In [38]:
# Define a Python list 'l'.
l = [0., 0.5, 1.5, 3., 5.]
# Multiply the list 'l' by 2. For lists, this results in concatenation.
2 *l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [39]:
# Display the current state of array 'a'.
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [40]:
# Multiply each element of the NumPy array 'a' by 2 (element-wise multiplication).
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

In [41]:
# Raise each element of the NumPy array 'a' to the power of 2 (element-wise exponentiation).
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.], dtype=float32)

In [42]:
# Calculate 2 raised to the power of each element in array 'a' (element-wise exponentiation).
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.], dtype=float32)

In [43]:
# Raise each element of array 'a' to the power of itself (element-wise exponentiation).
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05], dtype=float32)

In [44]:
# Calculate the exponential of each element in array 'a' (e raised to the power of each element).
np.exp(a)

array([1.0000000e+00, 2.7182820e+00, 7.3890557e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342877e+02, 1.0966332e+03],
      dtype=float32)

In [45]:
# Calculate the square root of each element in array 'a'.
np.sqrt(a)

array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512], dtype=float32)

In [46]:
# Calculate the square root of the scalar value 2.5 using NumPy's sqrt function.
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [47]:
# Import the math module.
import math

In [48]:
# Calculate the square root of the scalar value 2.5 using Python's built-in math.sqrt function.
math.sqrt(2.5)

1.5811388300841898

In [49]:
# Measure the execution time of calculating the square root of 2.5 using NumPy's sqrt function.
%timeit np.sqrt(2.5)

1.64 µs ± 366 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [50]:
# Measure the execution time of calculating the square root of 2.5 using Python's built-in math.sqrt function.
%timeit math.sqrt(2.5)

55.5 ns ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# **Multiple Dimensions**

In [51]:
import numpy as np
# Create a 2D NumPy array 'b' by stacking array 'a' and 'a' multiplied by 2.
b = np.array([a, a * 2])
# Display the array 'b'.
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]], dtype=float32)

In [52]:
# Access and display the first row (at index 0) of the 2D array 'b'.
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [53]:
# Access and display the element at the first row (index 0) and third column (index 2) of array 'b'.
b[0, 2]

np.float32(2.0)

In [54]:
# Access and display elements from all rows (:) at the second column (index 1) of array 'b'.
b[:,1]

array([1., 2.], dtype=float32)

In [55]:
# Calculate and display the sum of all elements in the array 'b'.
b.sum()

np.float32(84.0)

In [56]:
# Calculate and display the sum of elements along columns (axis=0) in array 'b'.
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.], dtype=float32)

In [57]:
# Calculate and display the sum of elements along rows (axis=1) in array 'b'.
b.sum(axis=1)

array([28., 56.], dtype=float32)

In [58]:
# Create a 2x3 NumPy array 'c' filled with zeros, with integer data type and C-style order.
c = np.zeros((2, 3), dtype='i', order='C')
# Display array 'c'.
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
# Create a 3D NumPy array 'c' of shape (2, 3, 4) filled with ones, with integer data type and C-style order.
c = np.ones((2, 3, 4), dtype='i', order='C')
# Display array 'c'.
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [60]:
# Create a new array 'd' with the same shape and data type as array 'c', filled with uninitialized data (effectively zeros in many cases), with float16 data type and C-style order.
d = np.zeros_like(c, dtype='f16', order='C')
# Display array 'd'.
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [61]:
# Create a new array 'd' with the same shape and data type as array 'c', filled with ones, with float16 data type and C-style order.
d = np.ones_like(c, dtype='f16', order='C')
# Display array 'd'.
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [62]:
# Create a new array 'e' of shape (2, 3, 2) with uninitialized data. The contents will be whatever is in memory at that location.
e = np.empty((2, 3, 2))
# Display array 'e'.
e

array([[[1.35656314e-315, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.75380097e+030]]])

In [63]:
# Create a new array 'f' with the same shape and data type as array 'c', filled with uninitialized data.
f = np.empty_like(c)
# Display array 'f'.
f

array([[[ 274571437,          0,          0,          0],
        [         0,          0,          0,          0],
        [         0,          0,          0,          0]],

       [[         0,          0,          0,          0],
        [         0,          0,          0,          0],
        [         0,          0,          0, 1179516974]]], dtype=int32)

In [64]:
# Create a 5x5 identity matrix using np.eye().
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
# Create a NumPy array 'g' with 12 evenly spaced values between 5 and 15 (inclusive).
g = np.linspace(5, 15, 12)
# Display array 'g'.
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

# **Meta information**

In [66]:
# Display the total number of elements in the array 'g'.
g.size

12

In [67]:
# Display the size in bytes of each element in the array 'g'.
g.itemsize

8

In [68]:
# Display the number of dimensions (axes) of the array 'g'.
g.ndim

1

In [69]:
# Display the shape of the array 'g' (a tuple indicating the size of each dimension).
g.shape

(12,)

In [70]:
# Display the data type of the elements in the array 'g'.
g.dtype

dtype('float64')

In [71]:
# Display the total number of bytes consumed by the elements of the array 'g'.
g.nbytes

96

# **Reshaping, Resizing, Stacking, Flattening**

In [72]:
g = np.arange(15)
# Display the array 'g'.
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
# Display the shape of the array 'g'.
g.shape

(15,)

In [74]:
# Display the shape of the array 'g' using np.shape().
np.shape(g)

(15,)

In [76]:
# Reshape the array 'g' into a 3x5 matrix and display the result.
g.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
# Reshape the array 'g' into a 5x3 matrix and assign it to variable 'h', then display 'h'.
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [78]:
# Display the transpose of array 'h'.
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [79]:
# Display the transpose of array 'h' using the transpose() method.
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [80]:
# Display the current state of array 'g'.
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
# Resize the array 'g' to a shape of (3, 1) and display the result.
np.resize(g, (3, 1))

array([[0],
       [1],
       [2]])

In [82]:
# Resize the array 'g' to a shape of (1, 5) and display the result.
np.resize(g, (1, 5))

array([[0, 1, 2, 3, 4]])

In [83]:
# Resize the array 'g' to a shape of (2, 5) and display the result.
np.resize(g, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
# Resize the array 'g' to a shape of (5, 4), assign it to 'n', and display 'n'. Note that resizing to a larger size repeats the original array elements.
n = np.resize(g, (5, 4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [85]:
# Display the current state of array 'h'.
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [86]:
# Horizontally stack array 'h' and 'h' multiplied by 2, then display the result.
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [87]:
# Vertically stack array 'h' and 'h' multiplied by 0.5, then display the result.
np.vstack((h, 0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [88]:
# Display the current state of array 'h'.
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [89]:
# Flatten the array 'h' into a 1D array (row-major order by default) and display the result.
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
# Flatten the array 'h' into a 1D array using C-style (row-major) order and display the result.
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
# Flatten the array 'h' into a 1D array using Fortran-style (column-major) order and display the result.
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [92]:
# Iterate through the flattened array 'h' (row-major order by default) and print each element followed by a comma.
for i in h.flat:
  print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [93]:
# Iterate through the array 'h' using ravel (which returns a view or copy depending on the order and original array) in C-style (row-major) order and print each element followed by a comma.
for i in h.ravel(order='C'):
  print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [95]:
# Iterate through the array 'h' using ravel (which returns a view or copy depending on the order and original array) in Fortran-style (column-major) order and print each element followed by a comma.
for i in h.ravel(order='F'):
  print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,