<a href="https://colab.research.google.com/github/Saifullah785/python-for-finance-notes/blob/main/Chapter_01_why_Python_for_finance/Chapter_01_why_Python_for_finance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Why Python for Finance?**

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# **The Python Ecosystem**

In [2]:
100 * 2.5 + 50

300.0

In [3]:
import math

math.log(1)

0.0

# **Finace and Python Syntax**

In [4]:
import math
import numpy as np


In [11]:
S0 = 100.
k = 105.
T = 1.0
r = 0.05
sigma = 0.2

In [6]:
I = 100000

In [7]:
np.random.seed(1000)

In [9]:
z = np.random.standard_normal(I)
z

array([-0.20304183,  0.68167566,  0.39110433, ...,  1.3237382 ,
        0.97731072,  1.10401313])

In [14]:
ST = 50 * np.exp((r -sigma **2 /2) * T + sigma * math.sqrt(T) * z)
ST

array([49.47238518, 59.0484408 , 55.71469139, ..., 67.13937255,
       62.64508022, 64.25282118])

In [15]:
ht = np.maximum(ST - k, 0)
ht

array([0., 0., 0., ..., 0., 0., 0.])

In [17]:
C0 = math.exp(-r * T) * np.mean(ht)
C0

np.float64(0.00040005364395844255)

In [18]:
print('Value of the European call option: {:5.3f}.'.format(C0))

Value of the European call option: 0.000.


In [23]:
# %run bsm_mcs_euro.py

In [21]:
def bsm_mcs_euro(S0, K, T, r, sigma, I):
    ''' European call option value by Monte Carlo simulation.

    Parameters
    ==========
    S0 : float
        (initial) stock level
    K : float
        strike price
    T : float
        maturity date
    r : float
        risk-less short rate
    sigma : float
        volatility
    I : int
        number of random draws

    Returns
    =======
    C0 : float
        European call option present value
    '''
    z = np.random.standard_normal(I)
    ST = S0 * np.exp((r - 0.5 * sigma ** 2) * T + sigma * math.sqrt(T) * z)
    hT = np.maximum(ST - K, 0)
    C0 = math.exp(-r * T) * np.mean(hT)
    return C0

In [22]:
# Calculate the European call option price using the defined function
european_call_price = bsm_mcs_euro(S0, k, T, r, sigma, I)
print('Value of the European call option: {:5.3f}.'.format(european_call_price))

Value of the European call option: 7.958.
