<a href="https://colab.research.google.com/github/Saifullah785/python-for-finance-notes/blob/main/Chapter_06_Object_Oriented_Programming/Chapter_06_Object_Oriented_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Object Oriented Projgramming**

#Introduction

In [ ]:
# Defines a class named HumanBeing
class HumanBeing(object):
  # The __init__ method is the constructor of the class. It's called when a new object is created.
  def __init__(self, first_name, eye_color):
    # Initializes the instance variables (attributes) of the object.
    self.first_name = first_name
    self.eye_color = eye_color
    self.position = 0

  # Defines a method named walk_steps that takes an integer 'steps' as input.
  def walk_steps(self, steps):
    # Increases the value of the 'position' attribute by the 'steps' value.
    self.position += steps

In [ ]:
# Creates an instance of the HumanBeing class named 'sandra'
# with "Sandra" as the first name and "blue" as the eye color.
sandra = HumanBeing("Sandra", "blue")

In [ ]:
# Accesses and displays the 'first_name' attribute of the 'sandra' object.
sandra.first_name

'Sandra'

In [ ]:
# Accesses and displays the 'eye_color' attribute of the 'sandra' object.
sandra.eye_color

'blue'

In [ ]:
# Accesses and displays the 'position' attribute of the 'sandra' object.
sandra.position

0

In [ ]:
# Calls the 'walk_steps' method of the 'sandra' object with an argument of 5.
# This increases the 'position' attribute by 5.
sandra.walk_steps(5)

In [ ]:
# Accesses and displays the updated 'position' attribute of the 'sandra' object.
sandra.position

5

# A Brief Look at Standard Objects

In [ ]:
# Assigns the integer value 5 to the variable 'n'.
n = 5

In [ ]:
# Displays the data type of the variable 'n'.
type(n)

int

In [ ]:
# Accesses and displays the numerator of the integer 'n'.
# For an integer, the numerator is the integer itself.
n.numerator

5

In [ ]:
# Displays the 'bit_length' method of the integer 'n', which returns the number of bits required to represent an integer in binary.
n.bit_length

<function int.bit_length()>

In [ ]:
# Adds the value of 'n' to itself and displays the result.
n + n

10

In [ ]:
# Multiplies the value of 'n' by 2 and displays the result.
2 * n

10

In [ ]:
# Displays the memory size of the integer object 'n' in bytes.
n.__sizeof__()

28

# List

In [ ]:
# Creates a list named 'l' containing integers.
l = [1, 2, 3, 4]

In [ ]:
# Displays the data type of the variable 'l'.
type(l)

list

In [ ]:
# Accesses and displays the element at index 0 of the list 'l'.
l[0]

1

In [ ]:
# Appends the integer 10 to the end of the list 'l'.
l.append(10)

In [ ]:
# Displays the updated list 'l'.
l

[1, 2, 3, 4, 10]

In [ ]:
# Concatenates the list 'l' with itself and displays the result.
l + l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [ ]:
# Repeats the list 'l' twice and displays the result.
2 * l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [ ]:
# Calculates and displays the sum of all elements in the list 'l'.
sum(l)

20

In [ ]:
# Displays the memory size of the list object 'l' in bytes.
l.__sizeof__()

104

# **ndarray**

In [ ]:
# Imports the NumPy library and assigns it the alias 'np'.
import numpy as np

In [ ]:
# Creates a 4x4 NumPy array 'a' with values ranging from 0 to 15.
a = np.arange(16).reshape((4, 4))

In [ ]:
# Displays the NumPy array 'a'.
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Displays the data type of the 'a' object.
type(a)

numpy.ndarray

In [ ]:
# Displays the total number of bytes consumed by the elements of the array.
a.nbytes

128

In [ ]:
# Calculates and displays the sum of all elements in the NumPy array 'a'.
a.sum()

np.int64(120)

In [ ]:
# Displays the value of the NumPy integer.
np.int64(120)

np.int64(120)

In [ ]:
# Calculates and displays the cumulative sum of the elements along each column (axis=0) of the NumPy array 'a'.
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [ ]:
# Adds the NumPy array 'a' to itself element-wise and displays the result.
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
# Multiplies each element of the NumPy array 'a' by 2 and displays the result.
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
# Calculates and displays the sum of the elements along each column of the NumPy array 'a'.
sum(a)

array([24, 28, 32, 36])

In [ ]:
# Calculates and displays the sum of all elements in the NumPy array 'a' using the NumPy sum function.
np.sum(a)

np.int64(120)

In [ ]:
# Displays the memory size of the NumPy array object 'a' in bytes.
a.__sizeof__()

128

# **DataFrame**

In [ ]:
# Imports the pandas library and assigns it the alias 'pd'.
import pandas as pd

In [ ]:
# Creates a pandas DataFrame named 'df' from the NumPy array 'a'.
# The columns of the DataFrame are labeled 'a', 'b', 'c', and 'd'.
df = pd.DataFrame(a, columns=list('abcd'))

In [ ]:
# Displays the entire DataFrame 'df'.
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [ ]:
# Displays the data type of the 'df' object.
type(df)

pandas.core.frame.DataFrame

In [ ]:
# Displays the column labels of the DataFrame 'df'.
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# Calculates and displays the sum of each column in the DataFrame 'df'.
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [ ]:
# Calculates and displays the cumulative sum of each column in the DataFrame 'df'.
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [ ]:
# Adds the DataFrame 'df' to itself element-wise and displays the result.
df + df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [ ]:
# Multiplies each element of the DataFrame 'df' by 2 and displays the result.
2 * df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [ ]:
# Calculates and displays the sum of each column in the DataFrame 'df' using the NumPy sum function.
np.sum(df, axis=0)

a    24
b    28
c    32
d    36
dtype: int64

In [ ]:
# Displays the memory size of the DataFrame object 'df' in bytes.
df.__sizeof__()

260

# Basic of Python Classes

In [1]:
# Defines a class named FinancialInstrument.
# The 'pass' statement is a placeholder, indicating that the class has no attributes or methods yet.
class FinancialInstrument(object):
  pass

In [2]:
# Creates an instance of the FinancialInstrument class and assigns it to the variable 'fi'.
fi = FinancialInstrument()

In [3]:
# Displays the data type of the 'fi' object.
type(fi)

__main__.FinancialInstrument

In [4]:
# Displays the string representation of the 'fi' object, which includes its class and memory address.
fi

In [5]:
# Calls the '__str__' method of the 'fi' object, which returns a string representation of the object.
fi.__str__()

'<__main__.FinancialInstrument object at 0x7e83cea983d0>'

In [6]:
# Assigns the value 100 to a new attribute named 'price' of the 'fi' object.
fi.price = 100

In [7]:
# Accesses and displays the 'price' attribute of the 'fi' object.
fi.price

100

In [8]:
# Redefines the FinancialInstrument class with a class attribute 'author' and an '__init__' method.
# The '__init__' method initializes instance attributes 'symbol' and 'price'.
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price

In [9]:
# Accesses and displays the 'author' class attribute of the FinancialInstrument class.
FinancialInstrument.author

'Yves Hilpisch'

In [10]:
# Creates an instance of the new FinancialInstrument class named 'aapl'
# with 'AAPL' as the symbol and 100 as the price.
aapl = FinancialInstrument('AAPL', 100)

In [11]:
# Accesses and displays the 'symbol' attribute of the 'aapl' object.
aapl.symbol

'AAPL'

In [12]:
# Accesses and displays the 'author' class attribute through the 'aapl' instance.
aapl.author

'Yves Hilpisch'

In [13]:
# Updates the 'price' attribute of the 'aapl' object to 105.
aapl.price = 105

In [14]:
# Accesses and displays the updated 'price' attribute of the 'aapl' object.
aapl.price

105

In [15]:
# Redefines the FinancialInstrument class, inheriting from the previous version.
# It adds two methods: 'get_price' to return the price and 'set_price' to update the price.
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price

In [16]:
# Creates a new instance of the modified FinancialInstrument class.
fi = FinancialInstrument('AAPL', 100)

In [17]:
# Calls the 'get_price' method of the 'fi' object to retrieve the price.
fi.get_price()

100

In [18]:
# Calls the 'set_price' method of the 'fi' object to update the price to 105.
fi.set_price(105)

In [19]:
# Calls the 'get_price' method again to display the updated price.
fi.get_price()

105

In [20]:
# Accesses and displays the 'price' attribute directly.
fi.price

105

In [21]:
# Redefines the FinancialInstrument class to use a private attribute for price.
# The '__price' attribute is intended to be accessed only through the 'get_price' and 'set_price' methods.
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [22]:
# Creates an instance of the FinancialInstrument class with a private price attribute.
fi = FinancialInstrument('AAPL', 100)

In [23]:
# Calls the 'get_price' method to access the private '__price' attribute.
fi.get_price()

100

In [24]:
# Accesses the "mangled" name of the private attribute '__price'.
# This is not a recommended practice but is possible in Python.
fi._FinancialInstrument__price

100

In [25]:
# Directly modifies the "mangled" private attribute.
fi._FinancialInstrument__price = 105

In [26]:
# Calls the 'set_price' method to change the price back to 100.
fi.set_price(100)

In [27]:
# Defines a PortfolioPosition class that holds a FinancialInstrument object and a position size.
# It includes methods to get and update the position size, and to calculate the position's value.
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
               self.position.get_price()

In [28]:
# Creates an instance of the PortfolioPosition class,
# using the 'fi' object and a position size of 10.
pp = PortfolioPosition(fi, 10)

In [29]:
# Calls the 'get_position_size' method to retrieve the position size.
pp.get_position_size()

10

In [30]:
# Calls the 'get_position_value' method to calculate the total value of the position.
pp.get_position_value()

1000

In [31]:
# Accesses the 'get_price' method of the 'FinancialInstrument' object held within the 'PortfolioPosition' object.
pp.position.get_price()

100

In [32]:
# Calls the 'set_price' method of the 'FinancialInstrument' object to update the price to 105.
pp.position.set_price(105)

In [34]:
# Calls the 'get_position_value' method again to show the updated value.
pp.get_position_value()

1050